In [61]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
#Bir sınıflandırma problemi çünkü veri setinin en sonunda müşterinin bankadan çıkıp çıkmadığını gözlemliyoruz

#It is a classification problem because at the end of the dataset, we observe whether the customer has left the bank or not.

In [63]:
df = pd.read_csv(r"C:\db\Churn_Modelling.csv")

In [65]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [67]:
df = df.drop(columns =["RowNumber","CustomerId","Surname"])

In [69]:
df = pd.get_dummies(df,columns=["Geography","Gender"],drop_first=True)

In [71]:
y =df["Exited"]
x = df.drop("Exited",axis =1)

In [73]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state=61,train_size=0.7)

In [75]:
rf = RandomForestClassifier()
model = rf.fit(x_train,y_train)
model.score(x_test,y_test)

0.8573333333333333

In [76]:
# %86 oranla bankanın müşterisi olup olmadığını anlayabiliyor

In [77]:
model.predict([[712,31,9,0,5,1,1,200000,False,False,True]])

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([1], dtype=int64)

In [80]:
dff=pd.DataFrame()

In [83]:
dff['takim']=["BJK","BJK","FB","GS","XY","XT","AB","AC","TS","AG","ANT","MIY","DBS","AG","AG","RM","BAR","SS","BDR"]

In [85]:
from sklearn.preprocessing import OneHotEncoder

In [87]:
ohe = OneHotEncoder()
xd = ohe.fit_transform(dff[["takim"]])

In [89]:
xd.toarray()

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.,

In [91]:
ohe.transform([["FB"]]).toarray()

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [106]:
df = pd.read_csv(r"C:\db\Churn_Modelling.csv")
df=df.drop(columns=["RowNumber","CustomerId","Surname"])

In [108]:
df.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1

In [110]:
ohe = OneHotEncoder()

In [112]:
xb = ohe.fit_transform(df[["Geography","Gender"]]).toarray()

In [116]:
ohe.get_feature_names_out()

array(['Geography_France', 'Geography_Germany', 'Geography_Spain',
       'Gender_Female', 'Gender_Male'], dtype=object)

In [118]:
xb = pd.DataFrame(xb)

In [120]:
xb.columns=ohe.get_feature_names_out()

In [122]:
xb

Geography_France  Geography_Germany  Geography_Spain  Gender_Female  \
0                  1.0                0.0              0.0            1.0   
1                  0.0                0.0              1.0            1.0   
2                  1.0                0.0              0.0            1.0   
3                  1.0                0.0              0.0            1.0   
4                  0.0                0.0              1.0            1.0   
...                ...                ...              ...            ...   
9995               1.0                0.0              0.0            0.0   
9996               1.0                0.0              0.0            0.0   
9997               1.0                0.0              0.0            1.0   
9998               0.0                1.0              0.0            0.0   
9999               1.0                0.0              0.0            1.0   

      Gender_Male  
0             0.0  
1             0.0  
2             0.0  
3             0.0  
4             0.0  
...           ...  
9995          1.0  
9996          1.0  
9997          0.0  
9998          1.0  
9999          0.0  

[10000 rows x 5 columns]

In [124]:
df.head(3)

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1

In [130]:
df = df.drop(columns=["Geography","Gender"])

In [132]:
df.head(3)

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   

   IsActiveMember  EstimatedSalary  Exited  
0               1        101348.88       1  
1               1        112542.58       0  
2               0        113931.57       1

In [134]:
df[xb.columns]=xb

In [136]:
df.head()

CreditScore  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619   42       2       0.00              1          1   
1          608   41       1   83807.86              1          0   
2          502   42       8  159660.80              3          1   
3          699   39       1       0.00              2          0   
4          850   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_France  \
0               1        101348.88       1               1.0   
1               1        112542.58       0               0.0   
2               0        113931.57       1               1.0   
3               0         93826.63       0               1.0   
4               1         79084.10       0               0.0   

   Geography_Germany  Geography_Spain  Gender_Female  Gender_Male  
0                0.0              0.0            1.0          0.0  
1                0.0              1.0            1.0          0.0  
2                0.0              0.0            1.0          0.0  
3                0.0              0.0            1.0          0.0  
4                0.0              1.0            1.0          0.0

In [138]:
y = df["Exited"]
x = df.drop("Exited",axis=1)


In [142]:
from sklearn.tree import DecisionTreeClassifier

In [148]:
tree = DecisionTreeClassifier()
model = tree.fit(x,y)
model.score(x,y)

1.0

overfitting oldu

In [155]:
ohe.transform([["France","Female"]]).toarray()

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(


array([[1., 0., 0., 1., 0.]])